# Generated by Django 2.1.15 on 2020-01-02 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('DOCTOR', 'Doctor'), ('RECEPTIONIST', 'Receptionist'), ('DENTREC', 'Receptionist for Dental'), ('PHARMACY', 'Pharmacy'), ('LABORATORY', 'Laboratory'), ('RADIATION', 'Radiation')], default='ADMIN', max_length=30),
        ),
    ]
