# Generated by Django 2.1.15 on 2020-04-15 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0003_auto_20200302_1145'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='email',
            new_name='user_id',
        ),
    ]
