# Generated by Django 2.1.15 on 2020-04-15 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0005_auto_20200415_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='division_type',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
