# Generated by Django 2.1.15 on 2020-04-15 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0006_user_division_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_of_resignation',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_of_employment',
            field=models.DateField(max_length=8, null=True),
        ),
    ]
