# Generated by Django 2.1.15 on 2020-04-16 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0008_user_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='classification',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
