# Generated by Django 2.1.15 on 2020-04-16 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0010_auto_20200416_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='depart_doctor',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='depart',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
