# Generated by Django 2.1.15 on 2020-04-17 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0011_auto_20200416_2300'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='resignation_memo',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
