# Generated by Django 2.1.15 on 2020-04-17 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0012_user_resignation_memo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='classification',
        ),
        migrations.AlterField(
            model_name='user',
            name='date_of_resignation',
            field=models.DateField(max_length=8, null=True),
        ),
    ]
