# Generated by Django 2.1.15 on 2020-06-17 21:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0013_auto_20200417_0020'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu', models.CharField(default='', max_length=8)),
                ('seq', models.IntegerField(default=0)),
                ('use_yn', models.CharField(default='Y', max_length=2)),
                ('creator', models.CharField(max_length=8)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('lastest_modified_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
