# Generated by Django 2.1.15 on 2020-06-17 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0014_user_menu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_menu',
            name='lastest_modified_date',
        ),
    ]
