# Generated by Django 2.1.15 on 2020-06-18 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0015_remove_user_menu_lastest_modified_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_menu',
            name='grp',
            field=models.CharField(default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='user_menu',
            name='seq',
            field=models.FloatField(default=0),
        ),
    ]
