# Generated by Django 2.1.15 on 2020-06-23 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0016_auto_20200618_0009'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_hidden',
            field=models.CharField(default='N', max_length=4),
        ),
    ]
