# Generated by Django 2.1.15 on 2020-06-25 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0017_user_is_hidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='connect_id',
            field=models.CharField(default='N', max_length=4),
        ),
    ]
