# Generated by Django 2.1 on 2019-12-08 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Receptionist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestManage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(max_length=32)),
                ('date_ordered', models.DateTimeField(null=True)),
                ('date_examination', models.DateTimeField(null=True)),
                ('date_expected', models.DateTimeField(null=True)),
                ('name_service', models.CharField(max_length=32, null=True)),
                ('progress', models.CharField(choices=[('new', 'new'), ('hold', 'hold'), ('done', 'done')], default='new', max_length=16)),
                ('manager', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Receptionist.TestManager')),
            ],
        ),
    ]
