# Generated by Django 2.1.15 on 2020-04-12 16:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Manage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='board_contents',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='board_contents',
            name='creator',
            field=models.CharField(default=2, max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='board_contents',
            name='lastest_modified_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='board_contents',
            name='lastest_modifier',
            field=models.CharField(default=2, max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='board_contents',
            name='use_yn',
            field=models.CharField(default='Y', max_length=2),
        ),
    ]
