# Generated by Django 2.1.15 on 2020-04-12 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manage', '0002_auto_20200412_1611'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_id', models.CharField(max_length=8)),
                ('groupno', models.IntegerField(default=0)),
                ('orderno', models.IntegerField(default=0)),
                ('depth', models.IntegerField(default=0)),
                ('comment', models.TextField()),
                ('use_yn', models.CharField(default='Y', max_length=2)),
                ('creator', models.CharField(max_length=8)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('lastest_modified_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
