# Generated by Django 2.1.15 on 2020-04-12 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Manage', '0003_comment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comment',
            new_name='Board_Comment',
        ),
    ]
