# Generated by Django 2.1.15 on 2020-04-12 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manage', '0004_auto_20200412_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='board_contents',
            name='is_notice',
            field=models.CharField(default='N', max_length=1),
        ),
    ]
