# Generated by Django 2.1.15 on 2020-04-21 02:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Manage', '0005_board_contents_is_notice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board_File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_id', models.CharField(max_length=8, null=True)),
                ('file', models.FileField(null=True, upload_to='board/')),
                ('registered_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('use_yn', models.CharField(default='Y', max_length=2)),
            ],
        ),
        migrations.RemoveField(
            model_name='board_contents',
            name='is_notice',
        ),
        migrations.AddField(
            model_name='board_contents',
            name='board_type',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='board_contents',
            name='date_done',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='board_contents',
            name='date_to_be_done',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='board_contents',
            name='depart_from',
            field=models.CharField(default=None, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='board_contents',
            name='options',
            field=models.CharField(default=None, max_length=8, null=True),
        ),
    ]
