# Generated by Django 2.1.15 on 2020-04-21 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manage', '0007_auto_20200421_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='board_contents',
            name='top_seq',
            field=models.CharField(default=0, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='board_contents',
            name='view_count',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='board_contents',
            name='options',
            field=models.CharField(default='GENERAL', max_length=8, null=True),
        ),
    ]
