# Generated by Django 2.1.15 on 2020-04-21 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manage', '0009_auto_20200421_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='board_contents',
            name='depart_to',
            field=models.CharField(default=None, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='board_contents',
            name='status',
            field=models.CharField(default=None, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='board_contents',
            name='depart_from',
            field=models.CharField(default=None, max_length=16, null=True),
        ),
    ]
