# Generated by Django 2.1.15 on 2020-04-21 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manage', '0010_auto_20200421_1920'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board_View_Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_id', models.CharField(max_length=8, null=True)),
                ('user_id', models.CharField(max_length=8, null=True)),
                ('registered_date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='board_contents',
            name='date_done',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
