# Generated by Django 2.1.15 on 2020-04-22 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manage', '0011_auto_20200421_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board_contents',
            name='date_done',
            field=models.CharField(default='0000-00-00 00:00:00', max_length=20),
        ),
        migrations.AlterField(
            model_name='board_contents',
            name='date_to_be_done',
            field=models.CharField(default='0000-00-00 00:00:00', max_length=20),
        ),
        migrations.AlterField(
            model_name='board_contents',
            name='depart_from',
            field=models.CharField(default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='board_contents',
            name='depart_to',
            field=models.CharField(default='', max_length=8),
        ),
        migrations.AlterField(
            model_name='board_contents',
            name='status',
            field=models.CharField(default='', max_length=8),
        ),
    ]
