# Generated by Django 2.1.15 on 2020-04-28 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manage', '0012_auto_20200422_0447'),
    ]

    operations = [
        migrations.CreateModel(
            name='Draft',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='', max_length=8)),
                ('type', models.CharField(default='', max_length=8)),
                ('depart', models.CharField(default='', max_length=8)),
                ('creator', models.CharField(default='', max_length=8)),
                ('date_registered', models.CharField(default='0000-00-00 00:00:00', max_length=20)),
                ('title', models.CharField(default='', max_length=256)),
                ('contents', models.TextField(default='')),
                ('additional', models.CharField(max_length=256, null=True)),
                ('modifier', models.CharField(max_length=8, null=True)),
                ('date_last_modified', models.CharField(default='0000-00-00 00:00:00', max_length=20)),
                ('date_in_charge', models.CharField(default='0000-00-00 00:00:00', max_length=20)),
                ('date_leader', models.CharField(default='0000-00-00 00:00:00', max_length=20)),
                ('date_accounting', models.CharField(default='0000-00-00 00:00:00', max_length=20)),
                ('date_ceo', models.CharField(default='0000-00-00 00:00:00', max_length=20)),
            ],
        ),
    ]
