# Generated by Django 2.1.15 on 2020-05-04 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manage', '0014_auto_20200503_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='draft',
            name='request_user',
            field=models.CharField(default='', max_length=64),
        ),
    ]
