# Generated by Django 2.1.15 on 2020-05-05 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manage', '0015_draft_request_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='draft',
            name='use_yn',
            field=models.CharField(default='Y', max_length=2),
        ),
    ]
