# Generated by Django 2.1.15 on 2020-05-05 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manage', '0017_board_file_board_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='board_file',
            name='memo',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='board_file',
            name='user',
            field=models.CharField(default='', max_length=64),
        ),
    ]
