# Generated by Django 2.1.15 on 2020-05-08 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manage', '0022_sms_history_receiver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sms_history',
            name='status',
            field=models.CharField(default='', max_length=8),
        ),
    ]
