# Generated by Django 2.1.15 on 2020-05-12 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manage', '0024_auto_20200511_2213'),
    ]

    operations = [
        migrations.AddField(
            model_name='draft',
            name='is_KBL',
            field=models.CharField(default='N', max_length=2),
        ),
    ]
