# Generated by Django 2.1.15 on 2020-05-20 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manage', '0026_auto_20200512_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sms_history',
            name='receiver',
            field=models.TextField(default=''),
        ),
    ]
