# Generated by Django 2.1.15 on 2020-05-28 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manage', '0027_auto_20200520_2326'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board_contents',
            old_name='depart_to',
            new_name='depart_to1',
        ),
        migrations.AddField(
            model_name='board_contents',
            name='depart_to2',
            field=models.CharField(default='', max_length=8),
        ),
        migrations.AddField(
            model_name='board_contents',
            name='depart_to3',
            field=models.CharField(default='', max_length=8),
        ),
        migrations.AddField(
            model_name='board_contents',
            name='depart_to4',
            field=models.CharField(default='', max_length=8),
        ),
    ]
