# Generated by Django 2.1.15 on 2020-06-12 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manage', '0028_auto_20200528_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='board_contents',
            name='depart_user_to1',
            field=models.CharField(default='', max_length=8),
        ),
        migrations.AddField(
            model_name='board_contents',
            name='depart_user_to2',
            field=models.CharField(default='', max_length=8),
        ),
        migrations.AddField(
            model_name='board_contents',
            name='depart_user_to3',
            field=models.CharField(default='', max_length=8),
        ),
        migrations.AddField(
            model_name='board_contents',
            name='depart_user_to4',
            field=models.CharField(default='', max_length=8),
        ),
    ]
