# Generated by Django 2.1.15 on 2020-06-15 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manage', '0029_auto_20200612_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='draft',
            name='request_type',
            field=models.CharField(default='', max_length=8),
        ),
    ]
