# Generated by Django 2.1.15 on 2020-06-15 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manage', '0030_draft_request_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='draft',
            name='payment_type',
            field=models.CharField(default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='draft',
            name='request_type',
            field=models.CharField(default='', max_length=16),
        ),
    ]
