# Generated by Django 2.1.15 on 2020-06-29 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manage', '0031_auto_20200615_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='draft',
            name='cost_name',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='draft',
            name='doc_num',
            field=models.CharField(default='', max_length=16),
        ),
        migrations.AddField(
            model_name='draft',
            name='doc_type',
            field=models.CharField(default='', max_length=16),
        ),
    ]
