# Generated by Django 2.1.15 on 2020-07-02 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manage', '0033_auto_20200630_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='board_comment',
            name='lastest_modifier',
            field=models.CharField(default='', max_length=8),
        ),
        migrations.AlterField(
            model_name='board_comment',
            name='creator',
            field=models.CharField(default='', max_length=8),
        ),
    ]
