# Generated by Django 2.1.15 on 2020-07-10 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manage', '0034_auto_20200702_1630'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_type', models.CharField(default='', max_length=20)),
                ('content_type', models.CharField(default='', max_length=16)),
                ('content_id', models.CharField(default='', max_length=8)),
                ('user_id', models.CharField(default='', max_length=20)),
                ('check_yn', models.CharField(default='N', max_length=2)),
                ('use_yn', models.CharField(default='Y', max_length=2)),
                ('pointed_date', models.CharField(default='0000-00-00 00:00:00', max_length=20)),
                ('creator', models.CharField(default='', max_length=8)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
