# Generated by Django 2.1.15 on 2020-08-26 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manage', '0036_alertlog_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScreenInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interval_sec', models.CharField(default='1', max_length=3)),
                ('text_interval_sec', models.CharField(default='1', max_length=3)),
                ('text_1', models.CharField(default='', max_length=60)),
                ('text_2', models.CharField(default='', max_length=60)),
                ('text_3', models.CharField(default='', max_length=60)),
                ('text_4', models.CharField(default='', max_length=60)),
                ('text_5', models.CharField(default='', max_length=60)),
                ('text_6', models.CharField(default='', max_length=60)),
                ('text_7', models.CharField(default='', max_length=60)),
                ('text_8', models.CharField(default='', max_length=60)),
                ('text_9', models.CharField(default='', max_length=60)),
                ('text_10', models.CharField(default='', max_length=60)),
                ('last_modifier', models.CharField(default='', max_length=8)),
                ('last_modified_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
