# Generated by Django 2.1.15 on 2020-08-28 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manage', '0037_screeninfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='board_comment',
            name='emoji1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='board_comment',
            name='emoji1_date',
            field=models.CharField(default='0000-00-00 00:00:00', max_length=20),
        ),
        migrations.AddField(
            model_name='board_comment',
            name='emoji2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='board_comment',
            name='emoji2_date',
            field=models.CharField(default='0000-00-00 00:00:00', max_length=20),
        ),
        migrations.AddField(
            model_name='board_comment',
            name='emoji3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='board_comment',
            name='emoji3_date',
            field=models.CharField(default='0000-00-00 00:00:00', max_length=20),
        ),
        migrations.AddField(
            model_name='board_comment',
            name='emoji4',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='board_comment',
            name='emoji4_date',
            field=models.CharField(default='0000-00-00 00:00:00', max_length=20),
        ),
    ]
