# Generated by Django 2.1.15 on 2020-05-12 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer_Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(default='', max_length=8)),
                ('type', models.CharField(default='', max_length=8)),
                ('name_kor', models.CharField(default='', max_length=32)),
                ('name_eng', models.CharField(default='', max_length=32)),
                ('ceo_name', models.CharField(default='', max_length=16)),
                ('business_type', models.CharField(default='', max_length=32)),
                ('corporation_no', models.CharField(default='', max_length=32)),
                ('count_employee', models.CharField(default='', max_length=6)),
                ('phone1', models.CharField(default='', max_length=16)),
                ('phone2', models.CharField(default='', max_length=16)),
                ('fax', models.CharField(default='', max_length=32)),
                ('add1', models.CharField(default='', max_length=128)),
                ('add2', models.CharField(default='', max_length=128)),
                ('memo', models.CharField(default='', max_length=256)),
                ('use_yn', models.CharField(default='Y', max_length=2)),
                ('registrant', models.CharField(default='', max_length=4)),
                ('modifier', models.CharField(default='', max_length=4)),
                ('date_done', models.CharField(default='0000-00-00 00:00:00', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Customer_Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='', max_length=8)),
                ('name_kor', models.CharField(default='', max_length=32)),
                ('name_eng', models.CharField(default='', max_length=32)),
                ('date_of_birth', models.CharField(default='0000-00-00', max_length=10)),
                ('passport_no', models.CharField(default='', max_length=16)),
                ('phone', models.CharField(default='', max_length=16)),
                ('add1', models.CharField(default='', max_length=128)),
                ('email', models.CharField(default='', max_length=64)),
                ('status', models.CharField(default='', max_length=16)),
                ('use_yn', models.CharField(default='Y', max_length=2)),
                ('registrant', models.CharField(default='', max_length=4)),
                ('modifier', models.CharField(default='', max_length=4)),
                ('date_done', models.CharField(default='0000-00-00 00:00:00', max_length=20)),
            ],
        ),
    ]
