# Generated by Django 2.1.15 on 2020-05-12 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KBL', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_employee',
            name='rank',
            field=models.CharField(default='', max_length=16),
        ),
    ]
