# Generated by Django 2.1.15 on 2020-05-13 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KBL', '0003_auto_20200513_1532'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project_Manage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(default='', max_length=16)),
                ('type', models.CharField(default='', max_length=16)),
                ('project_name', models.CharField(default='', max_length=32)),
                ('level', models.CharField(default='', max_length=16)),
                ('priority', models.CharField(default='', max_length=16)),
                ('start_date', models.CharField(default='0000-00-00 00:00:00', max_length=20)),
                ('end_date', models.CharField(default='0000-00-00 00:00:00', max_length=20)),
                ('expected_date', models.CharField(default='0000-00-00 00:00:00', max_length=20)),
                ('progress', models.CharField(default='', max_length=16)),
                ('in_charge', models.CharField(default='', max_length=32)),
                ('approval', models.CharField(default='', max_length=16)),
                ('note', models.CharField(default='', max_length=256)),
                ('use_yn', models.CharField(default='Y', max_length=2)),
                ('registrant', models.CharField(default='', max_length=4)),
                ('modifier', models.CharField(default='', max_length=4)),
                ('date_done', models.CharField(default='0000-00-00 00:00:00', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Project_Manage_Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.CharField(default='', max_length=16)),
                ('type', models.CharField(default='', max_length=16)),
                ('project_status', models.CharField(default='', max_length=16)),
                ('note', models.CharField(default='', max_length=256)),
                ('use_yn', models.CharField(default='Y', max_length=2)),
                ('registrant', models.CharField(default='', max_length=4)),
                ('modifier', models.CharField(default='', max_length=4)),
                ('date_done', models.CharField(default='0000-00-00 00:00:00', max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='estimate_sheet_detail',
            name='cost',
            field=models.CharField(default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='estimate_sheet_detail',
            name='note',
            field=models.CharField(default='', max_length=256),
        ),
    ]
