# Generated by Django 2.1.15 on 2020-05-13 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KBL', '0004_auto_20200513_1610'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work_Permit_Manage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.CharField(default='', max_length=8)),
                ('employee_id', models.CharField(default='', max_length=8)),
                ('type', models.CharField(default='', max_length=16)),
                ('project_name', models.CharField(default='', max_length=32)),
                ('level', models.CharField(default='', max_length=16)),
                ('priority', models.CharField(default='', max_length=16)),
                ('EA_application_date', models.CharField(default='0000-00-00 00:00:00', max_length=20)),
                ('EA_exp_date', models.CharField(default='0000-00-00 00:00:00', max_length=20)),
                ('WP_application_date', models.CharField(default='0000-00-00 00:00:00', max_length=20)),
                ('WP_exp_date', models.CharField(default='0000-00-00 00:00:00', max_length=20)),
                ('expected_date', models.CharField(default='0000-00-00 00:00:00', max_length=20)),
                ('submit_document', models.CharField(default='', max_length=16)),
                ('progress', models.CharField(default='', max_length=16)),
                ('note', models.CharField(default='', max_length=256)),
                ('use_yn', models.CharField(default='Y', max_length=2)),
                ('registrant', models.CharField(default='', max_length=4)),
                ('modifier', models.CharField(default='', max_length=4)),
                ('date_done', models.CharField(default='0000-00-00 00:00:00', max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='customer_employee',
            name='company_id',
            field=models.CharField(default='', max_length=8),
        ),
    ]
