# Generated by Django 2.1.15 on 2020-05-14 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KBL', '0006_auto_20200514_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_company',
            name='count_employee',
            field=models.CharField(default='0', max_length=6),
        ),
    ]
