# Generated by Django 2.1.15 on 2020-05-14 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KBL', '0008_customer_company_date_establishment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_company',
            name='date_establishment',
            field=models.CharField(default='0000-00-00', max_length=10),
        ),
    ]
