# Generated by Django 2.1.15 on 2020-05-14 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KBL', '0009_auto_20200514_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_company',
            name='condition',
            field=models.CharField(default='', max_length=8),
        ),
    ]
