# Generated by Django 2.1.15 on 2020-05-14 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KBL', '0011_auto_20200514_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_employee',
            name='memo',
            field=models.CharField(default='', max_length=256),
        ),
    ]
