# Generated by Django 2.1.15 on 2020-05-14 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KBL', '0012_customer_employee_memo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estimate_sheet',
            name='type',
        ),
        migrations.AddField(
            model_name='estimate_sheet_detail',
            name='type',
            field=models.CharField(default='', max_length=16),
        ),
    ]
