# Generated by Django 2.1.15 on 2020-05-14 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KBL', '0014_auto_20200514_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimate_sheet',
            name='classification',
            field=models.CharField(default='', max_length=16),
        ),
    ]
