# Generated by Django 2.1.15 on 2020-05-15 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KBL', '0016_estimate_sheet_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project_manage',
            old_name='date_done',
            new_name='date_modify',
        ),
        migrations.AddField(
            model_name='project_manage',
            name='customer_id',
            field=models.CharField(default='', max_length=8),
        ),
        migrations.AddField(
            model_name='project_manage',
            name='date_register',
            field=models.CharField(default='0000-00-00 00:00:00', max_length=20),
        ),
        migrations.AlterField(
            model_name='project_manage',
            name='customer_name',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='project_manage',
            name='level',
            field=models.CharField(default='', max_length=4),
        ),
        migrations.AlterField(
            model_name='project_manage',
            name='priority',
            field=models.CharField(default='', max_length=4),
        ),
        migrations.AlterField(
            model_name='project_manage',
            name='project_name',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='project_manage',
            name='type',
            field=models.CharField(default='', max_length=32),
        ),
    ]
