# Generated by Django 2.1.15 on 2020-05-16 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('KBL', '0017_auto_20200515_2312'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visa_Manage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.CharField(default='', max_length=8)),
                ('company_name', models.CharField(default='', max_length=64)),
                ('employee_id', models.CharField(default='', max_length=8)),
                ('employee_name', models.CharField(default='', max_length=32)),
                ('granted_company', models.CharField(default='', max_length=64)),
                ('type', models.CharField(default='', max_length=16)),
                ('date_entry', models.CharField(default='0000-00-00', max_length=10)),
                ('date_receipt_application', models.CharField(default='0000-00-00', max_length=10)),
                ('date_receipt_doc', models.CharField(default='0000-00-00', max_length=10)),
                ('date_subbmit_doc', models.CharField(default='0000-00-00', max_length=10)),
                ('date_expected', models.CharField(default='0000-00-00', max_length=10)),
                ('date_ordered', models.CharField(default='0000-00-00', max_length=10)),
                ('application_status', models.CharField(default='', max_length=20)),
                ('emergency', models.CharField(default='', max_length=20)),
                ('status', models.CharField(default='', max_length=20)),
                ('use_yn', models.CharField(default='Y', max_length=2)),
                ('registrant', models.CharField(default='', max_length=4)),
                ('date_register', models.CharField(default='0000-00-00 00:00:00', max_length=20)),
                ('modifier', models.CharField(default='', max_length=4)),
                ('date_modify', models.CharField(default='0000-00-00 00:00:00', max_length=20)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='KBL.Project_Manage')),
            ],
        ),
    ]
