# Generated by Django 2.1.15 on 2020-05-16 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('KBL', '0018_visa_manage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='work_permit_manage',
            old_name='date_done',
            new_name='date_modify',
        ),
        migrations.RenameField(
            model_name='work_permit_manage',
            old_name='level',
            new_name='status',
        ),
        migrations.RemoveField(
            model_name='work_permit_manage',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='work_permit_manage',
            name='progress',
        ),
        migrations.RemoveField(
            model_name='work_permit_manage',
            name='project_name',
        ),
        migrations.RemoveField(
            model_name='work_permit_manage',
            name='submit_document',
        ),
        migrations.RemoveField(
            model_name='work_permit_manage',
            name='type',
        ),
        migrations.AddField(
            model_name='work_permit_manage',
            name='company_name',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='work_permit_manage',
            name='date_register',
            field=models.CharField(default='0000-00-00 00:00:00', max_length=20),
        ),
        migrations.AddField(
            model_name='work_permit_manage',
            name='employee_name',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='work_permit_manage',
            name='project',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='KBL.Project_Manage'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='work_permit_manage',
            name='requiredment',
            field=models.CharField(default='', max_length=256),
        ),
    ]
