# Generated by Django 2.1.15 on 2020-05-16 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KBL', '0019_auto_20200516_2128'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project_manage_detail',
            old_name='date_done',
            new_name='date_modify',
        ),
        migrations.RemoveField(
            model_name='project_manage_detail',
            name='project_status',
        ),
        migrations.AddField(
            model_name='project_manage_detail',
            name='check',
            field=models.CharField(default='0', max_length=2),
        ),
        migrations.AddField(
            model_name='project_manage_detail',
            name='date',
            field=models.CharField(default='0000-00-00', max_length=10),
        ),
        migrations.AddField(
            model_name='project_manage_detail',
            name='date_register',
            field=models.CharField(default='0000-00-00 00:00:00', max_length=20),
        ),
        migrations.AddField(
            model_name='project_manage_detail',
            name='project_details',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='project_manage_detail',
            name='type',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='work_permit_manage',
            name='EA_application_date',
            field=models.CharField(default='0000-00-00', max_length=10),
        ),
        migrations.AlterField(
            model_name='work_permit_manage',
            name='EA_exp_date',
            field=models.CharField(default='0000-00-00', max_length=10),
        ),
        migrations.AlterField(
            model_name='work_permit_manage',
            name='WP_application_date',
            field=models.CharField(default='0000-00-00', max_length=10),
        ),
        migrations.AlterField(
            model_name='work_permit_manage',
            name='WP_exp_date',
            field=models.CharField(default='0000-00-00', max_length=10),
        ),
        migrations.AlterField(
            model_name='work_permit_manage',
            name='expected_date',
            field=models.CharField(default='0000-00-00', max_length=10),
        ),
    ]
