# Generated by Django 2.1.15 on 2020-05-17 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KBL', '0021_audit_manage'),
    ]

    operations = [
        migrations.AddField(
            model_name='audit_manage',
            name='check_account',
            field=models.CharField(default='0000-00-00', max_length=10),
        ),
        migrations.AddField(
            model_name='audit_manage',
            name='check_ceo',
            field=models.CharField(default='0000-00-00', max_length=10),
        ),
    ]
