# Generated by Django 2.1.15 on 2020-05-17 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KBL', '0022_auto_20200517_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='audit_manage',
            name='user_id_account',
            field=models.CharField(default='', max_length=8),
        ),
        migrations.AddField(
            model_name='audit_manage',
            name='user_id_ceo',
            field=models.CharField(default='', max_length=8),
        ),
        migrations.AddField(
            model_name='audit_manage',
            name='user_id_in_charge',
            field=models.CharField(default='', max_length=8),
        ),
        migrations.AddField(
            model_name='audit_manage',
            name='user_id_leader',
            field=models.CharField(default='', max_length=8),
        ),
    ]
