# Generated by Django 2.1.15 on 2020-05-17 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KBL', '0023_auto_20200517_1716'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice_Manage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(default='', max_length=10)),
                ('company_id', models.CharField(default='', max_length=8)),
                ('company_name', models.CharField(default='', max_length=64)),
                ('type', models.CharField(default='', max_length=64)),
                ('title', models.CharField(default='', max_length=64)),
                ('in_charge', models.CharField(default='', max_length=32)),
                ('date_sent', models.CharField(default='0000-00-00 00:00:00', max_length=20)),
                ('status', models.CharField(default='', max_length=20)),
                ('use_yn', models.CharField(default='Y', max_length=2)),
                ('registrant', models.CharField(default='', max_length=4)),
                ('date_register', models.CharField(default='0000-00-00 00:00:00', max_length=20)),
                ('modifier', models.CharField(default='', max_length=4)),
                ('date_modify', models.CharField(default='0000-00-00 00:00:00', max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='audit_manage',
            name='invoice',
            field=models.CharField(default='', max_length=8),
        ),
    ]
