# Generated by Django 2.1.15 on 2020-05-18 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('KBL', '0025_auto_20200517_2245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project_manage_detail',
            name='project_id',
        ),
        migrations.AddField(
            model_name='project_manage_detail',
            name='project',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='KBL.Project_Manage'),
            preserve_default=False,
        ),
    ]
