# Generated by Django 2.1.15 on 2020-05-18 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KBL', '0028_project_manage_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimate_sheet',
            name='date',
            field=models.CharField(default='0000-00-00 00:00:00', max_length=20),
        ),
    ]
