# Generated by Django 2.1.15 on 2020-05-21 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KBL', '0029_estimate_sheet_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='audit_manage',
            name='quantity',
            field=models.CharField(default='', max_length=4),
        ),
    ]
