# Generated by Django 2.1.15 on 2020-05-22 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KBL', '0031_auto_20200521_2359'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimate_sheet',
            name='is_sent',
            field=models.CharField(default='N', max_length=2),
        ),
        migrations.AlterField(
            model_name='estimate_sheet',
            name='date_sent',
            field=models.CharField(default='0000-00-00 00:00:00', max_length=20),
        ),
    ]
