# Generated by Django 2.1.15 on 2020-06-18 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KBL', '0033_invoice_manage_is_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimate_sheet',
            name='in_charge',
            field=models.CharField(default='', max_length=8),
        ),
    ]
