# Generated by Django 2.1.15 on 2020-06-18 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KBL', '0034_estimate_sheet_in_charge'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimate_sheet',
            name='in_charge_email',
            field=models.CharField(default='', max_length=128),
        ),
    ]
