# Generated by Django 2.1.15 on 2020-06-18 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KBL', '0035_estimate_sheet_in_charge_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimate_sheet',
            name='selected_acc',
            field=models.CharField(default='', max_length=256),
        ),
    ]
