# Generated by Django 2.1.15 on 2020-06-18 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KBL', '0036_estimate_sheet_selected_acc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estimate_sheet',
            name='selected_acc',
        ),
        migrations.AddField(
            model_name='invoice_manage',
            name='selected_acc',
            field=models.CharField(default='', max_length=256),
        ),
    ]
