# Generated by Django 2.1.15 on 2020-06-18 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KBL', '0037_auto_20200618_1123'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project_manage',
            old_name='in_charge',
            new_name='in_charge1',
        ),
        migrations.AddField(
            model_name='project_manage',
            name='in_charge2',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='project_manage',
            name='in_charge3',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='project_manage',
            name='in_charge4',
            field=models.CharField(default='', max_length=32),
        ),
    ]
