# Generated by Django 2.1.15 on 2020-06-22 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KBL', '0038_auto_20200618_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_employee',
            name='Identity_no',
            field=models.CharField(default='', max_length=32),
        ),
    ]
