# Generated by Django 2.1.15 on 2020-06-22 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KBL', '0039_customer_employee_identity_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_employee',
            name='name_vie',
            field=models.CharField(default='', max_length=32),
        ),
    ]
