# Generated by Django 2.1.15 on 2020-06-22 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KBL', '0041_auto_20200622_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_company',
            name='name_vie',
            field=models.CharField(default='', max_length=32),
        ),
    ]
