# Generated by Django 2.1.15 on 2020-07-07 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KBL', '0042_customer_company_name_vie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project_Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_id', models.CharField(max_length=8)),
                ('groupno', models.IntegerField(default=0)),
                ('orderno', models.IntegerField(default=0)),
                ('depth', models.IntegerField(default=0)),
                ('in_charge', models.CharField(default='', max_length=8)),
                ('start_date', models.CharField(default='0000-00-00 00:00:00', max_length=20)),
                ('end_date', models.CharField(default='0000-00-00 00:00:00', max_length=20)),
                ('expected_date', models.CharField(default='0000-00-00 00:00:00', max_length=20)),
                ('progress', models.CharField(default='', max_length=16)),
                ('comment', models.TextField()),
                ('use_yn', models.CharField(default='Y', max_length=2)),
                ('creator', models.CharField(default='', max_length=8)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('lastest_modifier', models.CharField(default='', max_length=8)),
                ('lastest_modified_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
