# Generated by Django 2.1.15 on 2020-07-07 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KBL', '0043_project_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_comment',
            name='content_type',
            field=models.CharField(default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='project_comment',
            name='content_id',
            field=models.CharField(default='', max_length=8),
        ),
    ]
