# Generated by Django 2.1.15 on 2020-07-15 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KBL', '0044_auto_20200707_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimate_sheet',
            name='is_VAT',
            field=models.CharField(default='N', max_length=1),
        ),
        migrations.AddField(
            model_name='estimate_sheet_detail',
            name='unit',
            field=models.CharField(default='', max_length=50),
        ),
    ]
