# Generated by Django 2.1.15 on 2020-08-24 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KBL', '0045_auto_20200715_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_employee',
            name='passport_expiration_date',
            field=models.CharField(default='0000-00-00', max_length=10),
        ),
        migrations.AddField(
            model_name='customer_employee',
            name='residence_expiration_date',
            field=models.CharField(default='0000-00-00', max_length=10),
        ),
        migrations.AddField(
            model_name='customer_employee',
            name='visa_expiration_date',
            field=models.CharField(default='0000-00-00', max_length=10),
        ),
        migrations.AddField(
            model_name='visa_manage',
            name='service_type',
            field=models.CharField(default='', max_length=16),
        ),
    ]
