# Generated by Django 2.1 on 2019-12-08 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Doctor', '0001_initial'),
        ('Receptionist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicineLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('changes', models.IntegerField()),
                ('memo', models.CharField(max_length=256, null=True)),
                ('type', models.CharField(choices=[('new', 'new'), ('add', 'add')], max_length=4)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Doctor.Medicine')),
                ('reception', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Receptionist.Reception')),
            ],
        ),
        migrations.CreateModel(
            name='MedicineManage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.CharField(choices=[('new', 'new'), ('hold', 'hold'), ('done', 'done')], default='new', max_length=16)),
                ('date_received', models.DateTimeField(null=True)),
                ('date_ordered', models.DateTimeField(auto_now_add=True)),
                ('diagnosis', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='Receptionist.Diagnosis')),
            ],
        ),
    ]
