# Generated by Django 2.1.15 on 2020-03-23 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pharmacy', '0002_auto_20200103_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicinelog',
            name='expiry_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='medicinelog',
            name='tmp_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='medicinelog',
            name='type',
            field=models.CharField(choices=[('new', 'new'), ('add', 'add'), ('dec', 'decrese'), ('del', 'deleted')], max_length=4),
        ),
    ]
