# Generated by Django 2.1.15 on 2020-02-23 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='COMMCODE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commcode', models.CharField(max_length=18, null=True)),
                ('commcode_name', models.CharField(max_length=18, null=True)),
                ('commcode_ncm', models.CharField(max_length=18, null=True)),
                ('use_yn', models.CharField(default='Y', max_length=1)),
                ('seq', models.CharField(max_length=18, null=True)),
                ('refr_col', models.CharField(max_length=18, null=True)),
                ('se1', models.CharField(max_length=18, null=True)),
                ('se2', models.CharField(max_length=18, null=True)),
                ('se3', models.CharField(max_length=18, null=True)),
                ('se4', models.CharField(max_length=18, null=True)),
            ],
        ),
    ]
