# Generated by Django 2.1.15 on 2020-02-23 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200223_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='commcode',
            name='se5',
            field=models.CharField(max_length=18, null=True),
        ),
    ]
