# Generated by Django 2.1.15 on 2020-02-24 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_commcode_se5'),
    ]

    operations = [
        migrations.AddField(
            model_name='commcode',
            name='se6',
            field=models.CharField(max_length=18, null=True),
        ),
        migrations.AddField(
            model_name='commcode',
            name='se7',
            field=models.CharField(max_length=18, null=True),
        ),
        migrations.AddField(
            model_name='commcode',
            name='se8',
            field=models.CharField(max_length=18, null=True),
        ),
    ]
