# Generated by Django 2.1.15 on 2020-04-16 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_notice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commcode',
            old_name='commcode_name',
            new_name='commcode_name_en',
        ),
        migrations.AddField(
            model_name='commcode',
            name='commcode_name_ko',
            field=models.CharField(max_length=18, null=True),
        ),
        migrations.AddField(
            model_name='commcode',
            name='commcode_name_vi',
            field=models.CharField(max_length=18, null=True),
        ),
        migrations.AddField(
            model_name='commcode',
            name='date_of_registered',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
