# Generated by Django 2.1.15 on 2020-04-16 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20200416_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='commcode',
            name='upper_commcode',
            field=models.CharField(max_length=18, null=True),
        ),
        migrations.AddField(
            model_name='commcode',
            name='upper_commcode_name',
            field=models.CharField(max_length=18, null=True),
        ),
    ]
