# Generated by Django 2.1.15 on 2020-04-16 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20200416_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='commcode',
            name='lastest_modified_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='commcode',
            name='lastest_modifier',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='commcode',
            name='registrerer',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
