# Generated by Django 2.1.15 on 2020-04-16 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20200416_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='commcode',
            name='commcode_grp_name',
            field=models.CharField(max_length=18, null=True),
        ),
    ]
