# Generated by Django 2.1.15 on 2020-04-17 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_commcode_commcode_grp_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='sms_test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=16, null=True)),
                ('content', models.CharField(max_length=80, null=True)),
                ('status', models.CharField(max_length=1, null=True)),
                ('res_code', models.CharField(max_length=1, null=True)),
                ('date_of_registered', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
