# Generated by Django 2.1.15 on 2020-04-17 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_sms_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sms_test',
            name='res_code',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='sms_test',
            name='status',
            field=models.CharField(default='2', max_length=1, null=True),
        ),
    ]
