# Generated by Django 2.1.15 on 2020-04-17 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20200417_1356'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sms_test',
            old_name='content',
            new_name='contents',
        ),
        migrations.RenameField(
            model_name='sms_test',
            old_name='phone_number',
            new_name='phone',
        ),
    ]
