# Generated by Django 2.1.15 on 2020-04-17 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20200417_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sms_test',
            name='date_of_registered',
            field=models.DateTimeField(null=True),
        ),
    ]
