# Generated by Django 2.1.15 on 2020-05-18 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20200417_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commcode',
            name='commcode',
            field=models.CharField(default='', max_length=18),
        ),
        migrations.AlterField(
            model_name='commcode',
            name='commcode_grp',
            field=models.CharField(default='', max_length=18),
        ),
        migrations.AlterField(
            model_name='commcode',
            name='commcode_grp_name',
            field=models.CharField(default='', max_length=18),
        ),
        migrations.AlterField(
            model_name='commcode',
            name='commcode_name_en',
            field=models.CharField(default='', max_length=18),
        ),
        migrations.AlterField(
            model_name='commcode',
            name='commcode_name_ko',
            field=models.CharField(default='', max_length=18),
        ),
        migrations.AlterField(
            model_name='commcode',
            name='commcode_name_vi',
            field=models.CharField(default='', max_length=18),
        ),
        migrations.AlterField(
            model_name='commcode',
            name='commcode_ncm',
            field=models.CharField(default='', max_length=18),
        ),
        migrations.AlterField(
            model_name='commcode',
            name='registrerer',
            field=models.CharField(default='', max_length=8),
        ),
        migrations.AlterField(
            model_name='commcode',
            name='se1',
            field=models.CharField(default='', max_length=18),
        ),
        migrations.AlterField(
            model_name='commcode',
            name='se2',
            field=models.CharField(default='', max_length=18),
        ),
        migrations.AlterField(
            model_name='commcode',
            name='se3',
            field=models.CharField(default='', max_length=18),
        ),
        migrations.AlterField(
            model_name='commcode',
            name='se4',
            field=models.CharField(default='', max_length=18),
        ),
        migrations.AlterField(
            model_name='commcode',
            name='se5',
            field=models.CharField(default='', max_length=18),
        ),
        migrations.AlterField(
            model_name='commcode',
            name='se6',
            field=models.CharField(default='', max_length=18),
        ),
        migrations.AlterField(
            model_name='commcode',
            name='se7',
            field=models.CharField(default='', max_length=18),
        ),
        migrations.AlterField(
            model_name='commcode',
            name='se8',
            field=models.CharField(default='', max_length=18),
        ),
        migrations.AlterField(
            model_name='commcode',
            name='seq',
            field=models.CharField(default='', max_length=18),
        ),
        migrations.AlterField(
            model_name='commcode',
            name='upper_commcode',
            field=models.CharField(default='', max_length=18),
        ),
        migrations.AlterField(
            model_name='commcode',
            name='upper_commcode_name',
            field=models.CharField(default='', max_length=18),
        ),
    ]
