# Generated by Django 2.1 on 2019-12-08 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('past_history', models.CharField(max_length=2048, null=True)),
                ('family_history', models.CharField(max_length=2048, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_kor', models.CharField(max_length=64)),
                ('name_eng', models.CharField(max_length=64)),
                ('phone', models.CharField(max_length=64)),
                ('gender', models.CharField(max_length=8)),
                ('date_of_birth', models.DateField(blank=True)),
                ('date_registered', models.DateTimeField(auto_now_add=True)),
                ('tax', models.CharField(max_length=64, null=True)),
                ('address', models.CharField(max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TaxInvoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=2048, null=True)),
                ('company_name', models.CharField(max_length=2048, null=True)),
                ('address', models.CharField(max_length=2048, null=True)),
                ('patient', models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Patient.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='Vital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('weight', models.CharField(max_length=8)),
                ('height', models.CharField(max_length=8)),
                ('blood_pressure', models.CharField(max_length=8)),
                ('blood_temperature', models.CharField(max_length=8)),
                ('breath', models.CharField(max_length=8)),
                ('purse_rate', models.CharField(max_length=8)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Patient.Patient')),
            ],
        ),
        migrations.AddField(
            model_name='history',
            name='patient',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Patient.Patient'),
        ),
    ]
