# Generated by Django 2.1.15 on 2019-12-29 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0002_auto_20191229_0031'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vital',
            old_name='purse_rate',
            new_name='pulse_rate',
        ),
    ]
