# Generated by Django 2.1.15 on 2019-12-29 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0003_auto_20191229_0151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='date_of_birth',
            field=models.DateField(blank=True),
        ),
    ]
