# Generated by Django 2.1.15 on 2020-03-30 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0007_auto_20200219_2203'),
    ]

    operations = [
        migrations.AddField(
            model_name='vital',
            name='reception',
            field=models.CharField(default=None, max_length=8, null=True),
        ),
    ]
