# Generated by Django 2.1.15 on 2020-04-10 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0008_vital_reception'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='email',
            field=models.CharField(default=None, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='memo',
            field=models.CharField(default=None, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='nationality',
            field=models.CharField(default=None, max_length=16, null=True),
        ),
    ]
