# Generated by Django 2.1.15 on 2020-04-29 00:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0009_auto_20200410_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='family_history',
            field=models.CharField(default='', max_length=2048),
        ),
        migrations.AlterField(
            model_name='history',
            name='past_history',
            field=models.CharField(default='', max_length=2048),
        ),
        migrations.AlterField(
            model_name='patient',
            name='email',
            field=models.CharField(default='', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='memo',
            field=models.CharField(default='', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='nationality',
            field=models.CharField(default='', max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='past_id',
            field=models.CharField(default='', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='taxinvoice',
            name='address',
            field=models.CharField(default='', max_length=2048),
        ),
        migrations.AlterField(
            model_name='taxinvoice',
            name='company_name',
            field=models.CharField(default='', max_length=2048),
        ),
        migrations.AlterField(
            model_name='taxinvoice',
            name='number',
            field=models.CharField(default='', max_length=2048),
        ),
        migrations.AlterField(
            model_name='taxinvoice',
            name='patient',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='Patient.Patient'),
        ),
    ]
