# Generated by Django 2.1.15 on 2020-04-29 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0010_auto_20200429_0013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='family_history',
            field=models.CharField(blank=True, default='', max_length=2048),
        ),
        migrations.AlterField(
            model_name='history',
            name='past_history',
            field=models.CharField(blank=True, default='', max_length=2048),
        ),
    ]
