# Generated by Django 2.1.15 on 2020-05-03 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0011_auto_20200429_0144'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='marking',
            field=models.CharField(default='', max_length=2, null=True),
        ),
    ]
