# Generated by Django 2.1.15 on 2020-06-18 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0014_auto_20200520_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='funnel',
            field=models.CharField(default='', max_length=2),
        ),
        migrations.AddField(
            model_name='patient',
            name='funnel_etc',
            field=models.CharField(default='', max_length=64),
        ),
    ]
