# Generated by Django 2.1.15 on 2022-07-13 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0015_auto_20200618_0322'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='category',
            field=models.CharField(default='', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='history_image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='receptionist'),
        ),
        migrations.AddField(
            model_name='patient',
            name='passport',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='taxinvoice',
            name='recommend',
            field=models.CharField(default='', max_length=2048),
        ),
    ]
