# Generated by Django 2.1.15 on 2024-03-23 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0017_auto_20231117_0602'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxinvoice',
            name='address_p',
            field=models.CharField(default='', max_length=2048),
        ),
        migrations.AddField(
            model_name='taxinvoice',
            name='memo',
            field=models.CharField(default='', max_length=2048),
        ),
    ]
