# Generated by Django 2.1.15 on 2020-07-12 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Receptionist', '0042_reservation_division'),
    ]

    operations = [
        migrations.CreateModel(
            name='NurseManage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=16, null=True)),
                ('date_done', models.DateTimeField(null=True)),
                ('use_yn', models.CharField(default='Y', max_length=2)),
                ('creator', models.CharField(default='', max_length=8)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('lastest_modifier', models.CharField(default='', max_length=8)),
                ('lastest_modified_date', models.DateTimeField(auto_now_add=True)),
                ('diagnosis', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='Receptionist.Diagnosis')),
            ],
        ),
    ]
