# Generated by Django 2.1.15 on 2020-07-13 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nurse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nursemanage',
            name='status',
            field=models.CharField(default='', max_length=16),
        ),
    ]
