# Generated by Django 2.1 on 2019-12-08 17:44

import Radiation.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Receptionist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RadiationManage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remark', models.CharField(max_length=32)),
                ('date_ordered', models.DateTimeField(auto_now_add=True)),
                ('name_service', models.CharField(max_length=32, null=True)),
                ('progress', models.CharField(choices=[('new', 'new'), ('done', 'done')], default='new', max_length=16)),
                ('image', models.ImageField(upload_to=Radiation.models.get_path)),
                ('manager', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Receptionist.PrecedureManager')),
            ],
        ),
    ]
