# Generated by Django 2.1.15 on 2019-12-27 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Radiation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='radiationmanage',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Receptionist.PrecedureManager'),
        ),
        migrations.AlterField(
            model_name='radiationmanage',
            name='remark',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
