# Generated by Django 2.1.15 on 2020-01-02 00:02

import Radiation.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Radiation', '0002_auto_20191227_0236'),
    ]

    operations = [
        migrations.CreateModel(
            name='RadiationImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=Radiation.models.get_path)),
                ('radiation_manage', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Radiation.RadiationManage')),
            ],
        ),
    ]
