# Generated by Django 2.1.15 on 2019-12-13 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='is_external',
            field=models.BooleanField(default=False),
        ),
    ]
