# Generated by Django 2.1.15 on 2019-12-16 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0002_test_is_external'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestRefferenceInterval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minimum', models.FloatField(null=True)),
                ('maximum', models.FloatField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='test',
            name='refference_interval',
        ),
        migrations.AddField(
            model_name='testrefferenceinterval',
            name='test',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Doctor.Test'),
        ),
    ]
