# Generated by Django 2.1.15 on 2019-12-16 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0003_auto_20191216_1428'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TestRefferenceInterval',
            new_name='TestReferenceInterval',
        ),
    ]
