# Generated by Django 2.1.15 on 2020-01-04 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0004_auto_20191216_1513'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pricechange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=128)),
                ('code', models.CharField(max_length=128)),
                ('date_start', models.CharField(max_length=8)),
                ('date_end', models.CharField(max_length=8)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
