# Generated by Django 2.1.15 on 2020-01-05 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0005_pricechange'),
    ]

    operations = [
        migrations.CreateModel(
            name='Precedure_short',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Doctor.Doctor')),
                ('precedure', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Doctor.Precedure')),
            ],
        ),
    ]
