# Generated by Django 2.1.15 on 2020-01-05 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0006_precedure_short'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Precedure_short',
            new_name='PrecedureShort',
        ),
    ]
