# Generated by Django 2.1.15 on 2020-01-05 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0007_auto_20200105_2258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='precedureshort',
            name='precedure',
        ),
        migrations.AddField(
            model_name='precedureshort',
            name='medicine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Doctor.Medicine'),
        ),
    ]
