# Generated by Django 2.1.15 on 2020-01-05 23:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0008_auto_20200105_2314'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicineShort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Doctor.Doctor')),
                ('medicine', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Doctor.Medicine')),
            ],
        ),
        migrations.RemoveField(
            model_name='precedureshort',
            name='medicine',
        ),
        migrations.AddField(
            model_name='precedureshort',
            name='precedure',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Doctor.Precedure'),
        ),
    ]
