# Generated by Django 2.1.15 on 2020-01-09 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0010_bundle'),
    ]

    operations = [
        migrations.AddField(
            model_name='bundle',
            name='name',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
    ]
