# Generated by Django 2.1.15 on 2020-01-09 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0011_bundle_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bundle',
            name='name',
        ),
    ]
