# Generated by Django 2.1.15 on 2020-01-09 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0012_remove_bundle_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='BundleClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upper', models.CharField(max_length=64)),
                ('group_code', models.CharField(max_length=64)),
                ('group_name', models.CharField(max_length=64)),
            ],
        ),
        migrations.RemoveField(
            model_name='bundle',
            name='group_code',
        ),
        migrations.RemoveField(
            model_name='bundle',
            name='group_name',
        ),
        migrations.AlterField(
            model_name='bundle',
            name='upper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Doctor.BundleClass'),
        ),
    ]
