# Generated by Django 2.1.15 on 2020-01-09 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0014_auto_20200109_1935'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bundleclass',
            old_name='user',
            new_name='upper',
        ),
    ]
