# Generated by Django 2.1.15 on 2020-02-29 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0015_auto_20200109_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='bundle',
            name='use_yn',
            field=models.CharField(default='Y', max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='examfee',
            name='use_yn',
            field=models.CharField(default='Y', max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='use_yn',
            field=models.CharField(default='Y', max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='precedure',
            name='use_yn',
            field=models.CharField(default='Y', max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='use_yn',
            field=models.CharField(default='Y', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='pricechange',
            name='date_end',
            field=models.CharField(max_length=18),
        ),
        migrations.AlterField(
            model_name='pricechange',
            name='date_start',
            field=models.CharField(max_length=18),
        ),
    ]
