# Generated by Django 2.1.15 on 2020-03-06 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0016_auto_20200229_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='price_input',
            field=models.IntegerField(default=0),
        ),
    ]
