# Generated by Django 2.1.15 on 2020-03-14 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0017_medicine_price_input'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examfee',
            name='code',
            field=models.CharField(default=1, max_length=8, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='medicine',
            name='code',
            field=models.CharField(default=1, max_length=8, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='precedure',
            name='code',
            field=models.CharField(default=1, max_length=8, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='test',
            name='code',
            field=models.CharField(default=1, max_length=8, unique=True),
            preserve_default=False,
        ),
    ]
