# Generated by Django 2.1.15 on 2020-03-20 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0020_auto_20200320_0923'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricechange',
            name='country',
            field=models.CharField(default='VI', max_length=4),
        ),
    ]
