# Generated by Django 2.1.15 on 2020-03-20 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0021_pricechange_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='precedure',
            name='type',
            field=models.CharField(default='NM', max_length=4),
        ),
    ]
