# Generated by Django 2.1.15 on 2020-03-20 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0022_precedure_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='multiple_level',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
