# Generated by Django 2.1.15 on 2020-03-20 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0023_medicine_multiple_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='name_display',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='country',
            field=models.CharField(max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='country_vie',
            field=models.CharField(max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='ingredient',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='name_vie',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='unit',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='unit_vie',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
