# Generated by Django 2.1.15 on 2020-03-20 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0024_auto_20200320_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='ingredient_vie',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
