# Generated by Django 2.1.15 on 2020-03-20 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0025_medicine_ingredient_vie'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicineclass',
            name='name_vie',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='precedureclass',
            name='name_vie',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='pricechange',
            name='type2',
            field=models.CharField(default=None, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='testclass',
            name='name_vie',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
