# Generated by Django 2.1.15 on 2020-03-28 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0026_auto_20200320_1629'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='unit',
        ),
        migrations.AddField(
            model_name='testreferenceinterval',
            name='unit',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='testreferenceinterval',
            name='unit_vie',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='testreferenceinterval',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Doctor.Test'),
        ),
    ]
