# Generated by Django 2.1.15 on 2020-03-29 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0027_auto_20200328_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='testreferenceinterval',
            name='remark',
            field=models.CharField(max_length=24, null=True),
        ),
    ]
