# Generated by Django 2.1.15 on 2020-03-30 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0028_testreferenceinterval_remark'),
    ]

    operations = [
        migrations.AddField(
            model_name='testreferenceinterval',
            name='gender',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
