# Generated by Django 2.1.15 on 2020-04-09 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0034_testreferenceinterval_use_yn'),
    ]

    operations = [
        migrations.AddField(
            model_name='depart',
            name='full_name',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='depart',
            name='full_name_vie',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
