# Generated by Django 2.1.15 on 2020-04-11 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0035_auto_20200409_0856'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='type',
            field=models.CharField(default='PHARM', max_length=10),
        ),
    ]
