# Generated by Django 2.1.15 on 2020-05-08 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0036_medicine_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='is_showing',
            field=models.CharField(default='Y', max_length=2),
        ),
    ]
