# Generated by Django 2.1.15 on 2020-06-06 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0038_precedure_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='testreferenceinterval',
            name='date_modify',
            field=models.CharField(default='0000-00-00 00:00:00', max_length=20),
        ),
        migrations.AddField(
            model_name='testreferenceinterval',
            name='date_register',
            field=models.CharField(default='0000-00-00 00:00:00', max_length=20),
        ),
        migrations.AddField(
            model_name='testreferenceinterval',
            name='modifier',
            field=models.CharField(default='', max_length=4),
        ),
        migrations.AddField(
            model_name='testreferenceinterval',
            name='registrant',
            field=models.CharField(default='', max_length=4),
        ),
        migrations.AlterField(
            model_name='testreferenceinterval',
            name='unit_vie',
            field=models.CharField(default='', max_length=4),
        ),
    ]
