# Generated by Django 2.1.15 on 2020-06-06 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0039_auto_20200606_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='testreferenceinterval',
            name='sign',
            field=models.CharField(default='', max_length=4),
        ),
        migrations.AlterField(
            model_name='testreferenceinterval',
            name='unit_vie',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
