# Generated by Django 2.1.15 on 2020-06-28 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0040_auto_20200606_1704'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='is_showing',
        ),
        migrations.AddField(
            model_name='medicine',
            name='red_invoice',
            field=models.CharField(default='N', max_length=2),
        ),
    ]
