# Generated by Django 2.1.15 on 2020-06-29 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0041_auto_20200628_2329'),
    ]

    operations = [
        migrations.AddField(
            model_name='precedureclass',
            name='code',
            field=models.CharField(default='', max_length=4),
        ),
    ]
