# Generated by Django 2.1.15 on 2020-06-29 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0042_precedureclass_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Depart_MedicineClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(max_length=8)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('depart', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Doctor.Depart')),
                ('medicine_class', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Doctor.MedicineClass')),
            ],
        ),
        migrations.CreateModel(
            name='Depart_PrecedureMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(max_length=8)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('depart', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Doctor.Depart')),
                ('precedure_class', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Doctor.PrecedureClass')),
            ],
        ),
        migrations.CreateModel(
            name='Depart_TestClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(max_length=8)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('depart', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Doctor.Depart')),
                ('test_class', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Doctor.TestClass')),
            ],
        ),
    ]
