# Generated by Django 2.1.15 on 2020-08-28 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0015_auto_20200618_0322'),
        ('Doctor', '0044_auto_20200629_1427'),
    ]

    operations = [
        migrations.CreateModel(
            name='VaccineHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccine_name', models.CharField(default='', max_length=64)),
                ('medicine_name', models.CharField(default='', max_length=64)),
                ('round', models.CharField(default='', max_length=64)),
                ('vaccine_date', models.DateTimeField(blank=True, null=True)),
                ('memo', models.CharField(default='', max_length=64)),
                ('creator', models.CharField(max_length=8)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modifier', models.CharField(max_length=8)),
                ('modified_date', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Patient.Patient')),
            ],
        ),
    ]
