# Generated by Django 2.1.15 on 2020-08-29 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0045_vaccinehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccinehistory',
            name='use_yn',
            field=models.CharField(default='Y', max_length=2),
        ),
    ]
