# Generated by Django 2.1.15 on 2020-08-29 01:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Receptionist', '0044_reception_is_vaccine'),
        ('Doctor', '0046_vaccinehistory_use_yn'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccinehistory',
            name='reception',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Receptionist.Reception'),
        ),
    ]
