# Generated by Django 2.1.15 on 2020-08-29 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0049_medicine_vaccine_hospital'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='vaccine_hospital',
        ),
        migrations.AddField(
            model_name='vaccinehistory',
            name='vaccine_hospital',
            field=models.CharField(default='I-MEDICARE', max_length=64),
        ),
    ]
