# Generated by Django 2.1.15 on 2023-08-23 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0051_medicineclass_use_yn'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='parent_test',
            field=models.ForeignKey(default=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Doctor.Test'),
        ),
    ]
