# Generated by Django 2.1.15 on 2023-08-25 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0052_test_parent_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='parent_test',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Doctor.Test'),
        ),
    ]
