# Generated by Django 2.1.15 on 2024-09-29 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0053_auto_20230825_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='examfee',
            name='name_vn',
            field=models.CharField(default='', max_length=124),
        ),
        migrations.AddField(
            model_name='examfee',
            name='tax_rate',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='medicine',
            name='tax_rate',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='precedure',
            name='tax_rate',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='test',
            name='tax_rate',
            field=models.IntegerField(default=0),
        ),
    ]
