# Generated by Django 2.1 on 2019-12-08 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Doctor', '0001_initial'),
        ('Patient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(max_length=2048, null=True)),
                ('assessment', models.CharField(max_length=2048, null=True)),
                ('objective_data', models.CharField(max_length=2048, null=True)),
                ('diagnosis', models.CharField(max_length=2048, null=True)),
                ('medical_report', models.CharField(max_length=2048, null=True)),
                ('recorded_date', models.DateTimeField(auto_now_add=True)),
                ('disease_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Doctor.Disease_Code')),
            ],
        ),
        migrations.CreateModel(
            name='ExamManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Receptionist.Diagnosis')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Doctor.ExamFee')),
            ],
        ),
        migrations.CreateModel(
            name='MedicineManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume', models.IntegerField(null=True)),
                ('amount', models.IntegerField(null=True)),
                ('days', models.IntegerField(null=True)),
                ('memo', models.CharField(max_length=256, null=True)),
                ('diagnosis', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Receptionist.Diagnosis')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Doctor.Medicine')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_total', models.IntegerField(null=True)),
                ('discounted', models.IntegerField(null=True)),
                ('total', models.IntegerField(null=True)),
                ('progress', models.CharField(choices=[('paid', 'paid'), ('unpaid', 'unpaid')], max_length=6)),
                ('memo', models.CharField(max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('cash', 'CASH'), ('card', 'CARD'), ('remit', 'Remit')], max_length=6)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('paid', models.IntegerField(null=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Receptionist.Payment')),
            ],
        ),
        migrations.CreateModel(
            name='PrecedureManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume', models.IntegerField(null=True)),
                ('amount', models.IntegerField(null=True)),
                ('days', models.IntegerField(null=True)),
                ('memo', models.CharField(max_length=256, null=True)),
                ('diagnosis', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Receptionist.Diagnosis')),
                ('precedure', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Doctor.Precedure')),
            ],
        ),
        migrations.CreateModel(
            name='Reception',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_date', models.DateTimeField(auto_now_add=True)),
                ('chief_complaint', models.CharField(max_length=2048)),
                ('progress', models.CharField(choices=[('new', 'new'), ('done', 'done')], default='new', max_length=16)),
                ('depart', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Doctor.Depart')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Doctor.Doctor')),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Patient.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(max_length=12)),
                ('report', models.TextField(max_length=2048, null=True)),
                ('usage', models.TextField(max_length=512, null=True)),
                ('date_of_hospitalization', models.DateTimeField()),
                ('date_of_publication', models.DateTimeField()),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Doctor.Doctor')),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Patient.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_date', models.DateTimeField()),
                ('name', models.CharField(max_length=64, null=True)),
                ('date_of_birth', models.DateTimeField(null=True)),
                ('phone', models.CharField(max_length=32, null=True)),
                ('memo', models.CharField(max_length=2048)),
                ('depart', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Doctor.Depart')),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Doctor.Doctor')),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Patient.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='TestManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume', models.IntegerField(null=True)),
                ('amount', models.IntegerField(null=True)),
                ('days', models.IntegerField(null=True)),
                ('memo', models.CharField(max_length=256, null=True)),
                ('diagnosis', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Receptionist.Diagnosis')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Doctor.Test')),
            ],
        ),
        migrations.AddField(
            model_name='reception',
            name='reservation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Receptionist.Reservation'),
        ),
        migrations.AddField(
            model_name='payment',
            name='reception',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='Receptionist.Reception'),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='reception',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='Receptionist.Reception'),
        ),
    ]
