# Generated by Django 2.1.15 on 2020-01-01 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Receptionist', '0002_auto_20200101_1047'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='discounted_percent',
            new_name='discounted',
        ),
    ]
