# Generated by Django 2.1.15 on 2020-01-09 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Receptionist', '0003_auto_20200101_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='reception',
            name='need_medical_report',
            field=models.BooleanField(default=False),
        ),
    ]
