# Generated by Django 2.1.15 on 2020-02-16 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Receptionist', '0005_auto_20200110_1638'),
    ]

    operations = [
        migrations.CreateModel(
            name='New_Patient_Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pain_location_img', models.CharField(max_length=512, null=True)),
                ('pain_location_text', models.CharField(max_length=512, null=True)),
                ('occurred_date', models.CharField(max_length=512, null=True)),
                ('treatment_history_yn', models.CharField(choices=[('1', '예'), ('0', '아니오')], max_length=1)),
                ('physiotherapy_yn', models.CharField(choices=[('1', '예'), ('0', '아니오')], max_length=1)),
                ('physiotherapy_count', models.CharField(max_length=512, null=True)),
                ('injection_treatment_yn', models.CharField(choices=[('1', '예'), ('0', '아니오')], max_length=1)),
                ('injection_treatment_count', models.CharField(max_length=512, null=True)),
                ('taking_medicine_yn', models.CharField(choices=[('1', '예'), ('0', '아니오')], max_length=1)),
                ('taking_medicine_count', models.CharField(max_length=512, null=True)),
                ('acupuncture_yn', models.CharField(choices=[('1', '예'), ('0', '아니오')], max_length=1)),
                ('acupuncture_count', models.CharField(max_length=512, null=True)),
                ('pain_level', models.CharField(max_length=512, null=True)),
                ('operation_yn', models.CharField(choices=[('1', '예'), ('0', '아니오')], max_length=1)),
                ('operation_name', models.CharField(max_length=512, null=True)),
                ('operation_year', models.CharField(max_length=512, null=True)),
                ('test_kinds', models.CharField(max_length=512, null=True)),
                ('test_etc', models.CharField(max_length=512, null=True)),
                ('disease_history_kinds', models.CharField(max_length=512, null=True)),
                ('disease_history_etc', models.CharField(max_length=512, null=True)),
                ('medication', models.CharField(max_length=512, null=True)),
                ('medicine_side_effects', models.CharField(choices=[('1', '예'), ('0', '아니오')], max_length=1)),
                ('pregnancy_yn', models.CharField(choices=[('0', '없음'), ('1', 'CD'), ('2', '필름')], max_length=512, null=True)),
                ('visit_motivation', models.CharField(max_length=512, null=True)),
                ('external_video', models.CharField(choices=[('1', '없음'), ('2', 'CD'), ('3', '필름')], max_length=1, null=True)),
                ('invoice_yn', models.CharField(max_length=512, null=True)),
                ('registered_date', models.CharField(max_length=512, null=True)),
                ('reception_date', models.CharField(max_length=512, null=True)),
            ],
        ),
    ]
