# Generated by Django 2.1.15 on 2020-02-17 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Receptionist', '0007_auto_20200216_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='first_visit_survey',
            name='cd_film_yn',
            field=models.CharField(choices=[('1', '없음'), ('2', 'CD'), ('3', '필름')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='first_visit_survey',
            name='pregnant_yn',
            field=models.CharField(choices=[('0', '해당없음'), ('1', '임신중'), ('2', '계획중')], max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='first_visit_survey',
            name='resv_date',
            field=models.DateTimeField(null=True),
        ),
    ]
