# Generated by Django 2.1.15 on 2020-02-17 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Receptionist', '0008_auto_20200217_0028'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FIRST_VISIT_SURVEY',
        ),
    ]
