# Generated by Django 2.1.15 on 2020-02-19 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Receptionist', '0012_auto_20200218_2034'),
    ]

    operations = [
        migrations.AddField(
            model_name='first_visit_survey',
            name='PT_vital',
            field=models.CharField(max_length=18, null=True),
        ),
    ]
