# Generated by Django 2.1.15 on 2020-02-19 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Receptionist', '0013_first_visit_survey_pt_vital'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosis',
            name='recommandation',
            field=models.CharField(max_length=2048, null=True),
        ),
    ]
