# Generated by Django 2.1.15 on 2020-02-19 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Receptionist', '0014_diagnosis_recommandation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diagnosis',
            old_name='recommandation',
            new_name='recommendation',
        ),
    ]
