# Generated by Django 2.1.15 on 2020-02-26 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Receptionist', '0015_auto_20200219_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reception',
            name='progress',
            field=models.CharField(choices=[('new', 'new'), ('deleted', 'deleted'), ('done', 'done')], default='new', max_length=16),
        ),
    ]
