# Generated by Django 2.1.15 on 2020-04-01 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Receptionist', '0016_auto_20200226_0235'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosis',
            name='ICD',
            field=models.CharField(max_length=512, null=True),
        ),
    ]
