# Generated by Django 2.1.15 on 2020-04-01 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Receptionist', '0017_diagnosis_icd'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosis',
            name='ICD_code',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
