# Generated by Django 2.1.15 on 2020-04-06 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Receptionist', '0019_report_reception'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='date_of_hospitalization',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='date_of_publication',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='serial',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
