# Generated by Django 2.1.15 on 2020-04-26 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Receptionist', '0021_auto_20200422_2318'),
    ]

    operations = [
        migrations.AddField(
            model_name='exammanager',
            name='is_checked_discount',
            field=models.CharField(default='0', max_length=1),
        ),
        migrations.AddField(
            model_name='medicinemanager',
            name='is_checked_discount',
            field=models.CharField(default=0, max_length=1),
        ),
        migrations.AddField(
            model_name='preceduremanager',
            name='is_checked_discount',
            field=models.CharField(default=0, max_length=1),
        ),
        migrations.AddField(
            model_name='testmanager',
            name='is_checked_discount',
            field=models.CharField(default=0, max_length=1),
        ),
    ]
