# Generated by Django 2.1.15 on 2020-04-29 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Receptionist', '0022_auto_20200426_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exammanager',
            name='is_checked_discount',
            field=models.CharField(default=False, max_length=8),
        ),
        migrations.AlterField(
            model_name='medicinemanager',
            name='is_checked_discount',
            field=models.CharField(default=False, max_length=8),
        ),
        migrations.AlterField(
            model_name='payment',
            name='additional',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='payment',
            name='discounted',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='payment',
            name='discounted_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='payment',
            name='memo',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='payment',
            name='sub_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='payment',
            name='total',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='preceduremanager',
            name='is_checked_discount',
            field=models.CharField(default=False, max_length=8),
        ),
        migrations.AlterField(
            model_name='testmanager',
            name='is_checked_discount',
            field=models.CharField(default=False, max_length=8),
        ),
    ]
