# Generated by Django 2.1.15 on 2020-05-19 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Receptionist', '0025_package_manage'),
    ]

    operations = [
        migrations.AddField(
            model_name='package_manage',
            name='grouping',
            field=models.CharField(default='1', max_length=4),
        ),
    ]
