# Generated by Django 2.1.15 on 2020-05-19 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Receptionist', '0026_package_manage_grouping'),
    ]

    operations = [
        migrations.AddField(
            model_name='package_manage',
            name='reception',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='Receptionist.Reception'),
            preserve_default=False,
        ),
    ]
