# Generated by Django 2.1.15 on 2020-05-19 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Receptionist', '0027_package_manage_reception'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package_manage',
            name='reception',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='Receptionist.Reception'),
        ),
    ]
