# Generated by Django 2.1.15 on 2020-05-19 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Receptionist', '0030_auto_20200519_1945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package_manage',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='package_manage',
            name='precedure',
        ),
        migrations.RemoveField(
            model_name='package_manage',
            name='reception',
        ),
        migrations.DeleteModel(
            name='Package_Manage',
        ),
    ]
