# Generated by Django 2.1.15 on 2020-06-08 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Receptionist', '0037_auto_20200527_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosis',
            name='sub_clinical_test',
            field=models.CharField(default='', max_length=2048),
        ),
    ]
