# Generated by Django 2.1.15 on 2020-06-11 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Receptionist', '0038_diagnosis_sub_clinical_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrecord',
            name='status',
            field=models.CharField(default='paid', max_length=10),
        ),
    ]
