# Generated by Django 2.1.15 on 2020-06-24 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Receptionist', '0040_paymentrecord_memo'),
    ]

    operations = [
        migrations.AddField(
            model_name='package_manage',
            name='precedure_mng_id',
            field=models.CharField(default='', max_length=4),
        ),
    ]
