# Generated by Django 2.1.15 on 2020-07-03 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Receptionist', '0041_package_manage_precedure_mng_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='division',
            field=models.CharField(default='', max_length=16),
        ),
    ]
