# Generated by Django 2.1.15 on 2020-08-26 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Receptionist', '0043_auto_20200824_0932'),
    ]

    operations = [
        migrations.AddField(
            model_name='reception',
            name='is_vaccine',
            field=models.BooleanField(default=False),
        ),
    ]
