# Generated by Django 2.1.15 on 2020-08-29 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Receptionist', '0044_reception_is_vaccine'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='re_reservation_date',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
