# Generated by Django 2.1.15 on 2022-11-30 22:45

import Receptionist.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Receptionist', '0046_auto_20220525_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='pay_time',
            field=models.DateTimeField(default=Receptionist.models.time_zero),
        ),
    ]
