# Generated by Django 2.1.15 on 2022-12-14 20:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0016_auto_20220713_2240'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Receptionist', '0047_payment_pay_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailMemo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(null=True)),
                ('memo', models.TextField()),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Patient.Patient')),
            ],
        ),
    ]
