# Generated by Django 2.1.15 on 2023-06-17 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0016_auto_20220713_2240'),
        ('Receptionist', '0048_detailmemo'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientNotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.TextField(max_length=256)),
                ('order', models.TextField(default='', null=True)),
                ('insurance', models.TextField(default='', null=True)),
                ('disease', models.TextField(default='', null=True)),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Patient.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='PatientRelative',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='', null=True)),
                ('relative', models.TextField(default='', null=True)),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Patient.Patient')),
            ],
        ),
        migrations.AddField(
            model_name='detailmemo',
            name='memo_depart',
            field=models.TextField(default='', null=True),
        ),
    ]
