# Generated by Django 2.1.15 on 2023-08-01 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Receptionist', '0049_auto_20230617_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='testmanager',
            name='status',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
