# Generated by Django 2.1.15 on 2023-08-28 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Receptionist', '0050_testmanager_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientrelative',
            name='person_id',
            field=models.TextField(default='', null=True),
        ),
    ]
