# Generated by Django 2.1.15 on 2023-09-25 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Receptionist', '0051_patientrelative_person_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosis',
            name='doctor_note',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='rec_note',
            field=models.TextField(default='', null=True),
        ),
    ]
