# Generated by Django 2.1.15 on 2023-10-06 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Receptionist', '0052_auto_20230925_1212'),
    ]

    operations = [
        migrations.CreateModel(
            name='DraftPatient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eng_name', models.CharField(default='', max_length=255)),
                ('kor_name', models.CharField(default='', max_length=255)),
                ('dob', models.CharField(default='', max_length=255)),
                ('gender', models.CharField(default='', max_length=255)),
                ('phone', models.CharField(default='', max_length=255)),
                ('email', models.CharField(default='', max_length=255)),
                ('address', models.CharField(default='', max_length=255)),
                ('company', models.CharField(default='', max_length=255)),
                ('note', models.CharField(default='', max_length=255)),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_registed', models.BooleanField(default=False)),
                ('founded_phone', models.BooleanField(default=False)),
                ('founded_eng_name', models.BooleanField(default=False)),
            ],
        ),
    ]
