# Generated by Django 2.1.15 on 2024-04-02 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Receptionist', '0055_reception_need_invoice_p'),
    ]

    operations = [
        migrations.AddField(
            model_name='reception',
            name='without_email',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='reception',
            name='without_name',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='reception',
            name='without_today',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
