# Generated by Django 2.1.15 on 2024-05-10 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Receptionist', '0057_reception_send_invoice_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='reception',
            name='need_insurance_p',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='reception',
            name='need_insurance_today',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='reception',
            name='need_invoice_p_today',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='reception',
            name='need_invoice_today',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='reception',
            name='without_day',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='reception',
            name='without_email_today',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
