# Generated by Django 2.1.15 on 2024-05-11 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Receptionist', '0058_auto_20240510_0053'),
    ]

    operations = [
        migrations.AddField(
            model_name='reception',
            name='need_insurance_p_today',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
