# Generated by Django 2.1.15 on 2024-05-25 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Receptionist', '0059_reception_need_insurance_p_today'),
    ]

    operations = [
        migrations.AddField(
            model_name='reception',
            name='memo_email',
            field=models.CharField(max_length=2048, null=True),
        ),
    ]
