# Generated by Django 2.1.15 on 2024-07-19 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Receptionist', '0060_reception_memo_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='TodayDoctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('depart', models.CharField(default='', max_length=255, null=True)),
                ('active_day', models.DateField()),
            ],
        ),
    ]
