# Generated by Django 2.1.15 on 2024-09-29 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Receptionist', '0061_todaydoctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='draftpatient',
            name='date_reservation',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='draftpatient',
            name='nation',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='draftpatient',
            name='symptom',
            field=models.CharField(default='', max_length=255),
        ),
    ]
