# Generated by Django 2.1.15 on 2024-12-08 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Receptionist', '0062_auto_20240928_2319'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListDoctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='draftpatient',
            name='depart',
            field=models.CharField(default='', max_length=255),
        ),
    ]
