# Generated by Django 2.1.15 on 2024-12-09 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Receptionist', '0063_auto_20241208_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='listdoctor',
            name='depart',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
